name: deskify
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_sliders: ^21.1.38
  provider: ^6.0.5
  uuid: ^3.0.7
  fl_chart: ^0.61.0
  reorderable_grid: ^1.0.6
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.6.0
  firebase_core: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
