name: deskify
description: An app for managing your height adjustable desk.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #! Backend
  # Service locator
  get_it: ^7.6.0
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  # Remote API
  internet_connection_checker: ^1.0.0+1
  firebase_core: ^2.11.0
  cloud_firestore: ^4.6.0

  #! Frontend
  syncfusion_flutter_sliders: ^21.1.38
  fl_chart: ^0.61.0
  reorderable_grid: ^1.0.6
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  fake_cloud_firestore: ^2.4.1+1

flutter:
  uses-material-design: true
